server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
fdfs:
  so-timeout: 1501 #读取数据超时时间
  connect-timeout: 601 #连接超时时间
  thumb-image: #缩略图配置
    width: 60
    height: 60
  tracker-list: # tracker地址 虚拟机服务器地址+端口（默认22122）
    - 192.168.209.200:22122