server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/disco_mall_study?serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.209.200
  rabbitmq:
    virtual-host: /leyou
    host: 192.168.209.200
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期